# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012

#  To make the extended ascii characters work on Windows
#  we need to set string encoding for jvm to utf-8 on windows
environment:
  SBT_OPTS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Dfile.encoding=UTF8
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt""" --version 0.13.15
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g

build_script:
  - mill ops[2.11.12].compile
  - mill amm[2.11.12].compile
  - mill integration[2.11.12].compile

test_script:
  - mill ops[2.11.12].test
  - mill amm[2.11.12].test
  - mill integration[2.11.12].test

cache:
  - C:\sbt\
  - '%USERPROFILE%\.ivy2\cache'
  - '%USERPROFILE%\.m2'
  - '%USERPROFILE%\.sbt'
  - '%LOCALAPPDATA%\Coursier\cache'
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
